name: env_ai
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - absl-py=2.3.1=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=pyhd8ed1ab_3
  - blas=1.0=mkl
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotli-python=1.1.0=py311h3e6a449_4
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py311h3485c13_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h3fd045d_2
  - cpuonly=2.0=0
  - cpython=3.11.13=py311hd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - flatbuffers=24.3.25=h63175ca_0
  - fonttools=4.60.1=py311h3f79411_0
  - freetype=2.14.1=h57928b3_0
  - gast=0.6.0=pyhd8ed1ab_0
  - giflib=5.2.2=h64bf75a_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py311h827c3e9_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - grpcio=1.71.0=py311h05171df_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.14.0=nompi_py311hc40ba4b_101
  - hdf5=1.14.6=nompi_he30205f_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.2=h63175ca_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - keras=3.11.2=pyh753f3f9_0
  - kiwisolver=1.4.9=py311h275cad7_1
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.15=ha5c8aab_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250127.0=cxx17_h4eb7d71_0
  - libaec=1.1.4=h20038f6_0
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libclang13=14.0.6=default_h77d9078_1
  - libcurl=8.15.0=h2300eb9_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgrpc=1.71.0=h35301be_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libkrb5=1.21.3=h885b0b7_4
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libpng=1.6.50=h7351971_1
  - libpq=17.4=h4a159e6_2
  - libprotobuf=5.29.3=he9d8c4a_0
  - libre2-11=2024.07.02=hd248061_3
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.5.1=h44ae7cf_1
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.13.8=h741aa76_1
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=20.1.8=h29ce207_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.9=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib=3.10.6=py311h1ea47a8_1
  - matplotlib-base=3.10.6=py311h1675fdf_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minizip=4.0.10=h9fa1bad_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=1.3.11=py311h5810407_1
  - mkl_random=1.2.8=py311h8683371_1
  - ml_dtypes=0.5.1=py311h11fd7f3_1
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyhd8ed1ab_1
  - namex=0.1.0=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=py311haa95532_0
  - numpy=2.1.3=py311h12f7302_2
  - numpy-base=2.1.3=py311he4e2855_2
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.5.4=h725018a_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.17.0=py311h3fd045d_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=9.4.0=py311h76d9071_1
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - protobuf=5.29.3=py311hda3d55a_0
  - psutil=7.1.0=py311h3485c13_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.7.2=py311h2e8c42f_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.13=h3f84c4b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-flatbuffers=24.3.25=pyhe33e51e_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py311hefeebc8_1
  - pyzmq=27.1.0=py311hb77b9c8_0
  - qhull=2020.2=hc790b64_5
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtshadertools=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebengine=6.7.2=h601c93c_0
  - qtwebsockets=6.7.3=h885b0b7_1
  - re2=2024.07.02=haf4117d_3
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - scikit-learn=1.7.2=py311h8a15ebc_0
  - scipy=1.16.2=py311h86a6471_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=72.1.0=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_0
  - sqlite=3.50.4=hdb435a2_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py311h17033d2_1
  - sympy=1.14.0=py311haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tensorboard-data-server=0.7.0=py311h1ea47a8_3
  - tensorflow-base=2.19.1=cpu_py311h4cf5749_0
  - termcolor=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_2
  - tornado=6.5.2=py311h3485c13_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=16.0.0=py311h3485c13_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.3=py311h3485c13_1
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zstandard=0.25.0=py311hf893f09_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - accelerate==1.11.0
      - annotated-types==0.7.0
      - blis==1.3.0
      - catalogue==2.0.10
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - cymem==2.0.11
      - en-core-web-sm==3.8.0
      - filelock==3.20.0
      - fsspec==2025.9.0
      - huggingface-hub==0.35.3
      - langcodes==3.5.0
      - language-data==1.3.0
      - libclang==18.1.1
      - marisa-trie==1.3.1
      - murmurhash==1.0.13
      - preshed==3.0.10
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyyaml==6.0.3
      - safetensors==0.6.2
      - shellingham==1.5.4
      - smart-open==7.4.0
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - tensorboard==2.20.0
      - tensorflow==2.20.0
      - textblob==0.19.0
      - tf-keras==2.20.1
      - thinc==8.3.6
      - tokenizers==0.22.1
      - torch==2.9.0+cpu
      - torchaudio==2.9.0+cpu
      - torchvision==0.24.0+cpu
      - transformers==4.57.1
      - typer==0.20.0
      - typing-inspection==0.4.2
      - vadersentiment==3.3.2
      - wasabi==1.1.3
      - weasel==0.4.1
prefix: C:\Users\Jamal Arshad\miniconda3\envs\env_ai
